GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs
content-type: application/json

{
      "title": "mongoDB",
      "author": "Aarju",
      "userId":"659e3395da65146279eff6ad",
      "url":"http://localhost:3001/api/notes/123",
      "likes":100

  }
###
DELETE  http://localhost:3003/api/blogs/6596935f58c4ce640f986f66
###

PUT http://localhost:3003/api/blogs/659bb285e8ef6ba652199894
Content-Type: application/json

{
    "title":"blog1",
    "author":"AarjuPariyar",
    "url":"http://localhost:3001/api/notes/id",
    "likes":75
}
###

GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"King5",
    "name":"kingKhan1234",
    "password":"geeta123"

}

