GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFhcmp1MjA1NyIsImlkIjoiNjViY2JlNmIxZDBmYzQ3NjVmOWI2MjkzIiwiaWF0IjoxNzA2ODY4NDE0LCJleHAiOjE3MDY4NzIwMTR9.xHf8qgWTy4O5g2cIX_hldvDSBkLD1wu9GPxP-JtU26Y

{
    "title": "HEllo Coder",
    "author": "Aarju375",
    "userId":"12345678345678a",
    "url":"http://localhost:2001/api/notes/123",
    "likes":1000
}

###
DELETE  http://localhost:3003/api/blogs/659e4c661dc3b083178570ca
###

PUT http://localhost:3003/api/blogs/65bc799e6cc53d2e75e6c0d3
Content-Type: application/json

{
    "title":"blog1",
    "author":"AarjuPariyar",
    "url":"http://localhost:3001/api/notes/id",
    "likes":75
}
###

GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"Aarju2057",
    "name":"Aarju_Pariyar",
    "password":"25-Aug"

}
###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"Aarju2057",
    "password":"25-Aug"
}
###

DELETE  http://localhost:3003/api/blogs/65bcbf5a1d0fc4765f9b6297
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFhcmp1MjA1NyIsImlkIjoiNjViY2JlNmIxZDBmYzQ3NjVmOWI2MjkzIiwiaWF0IjoxNzA2ODcyODY4LCJleHAiOjE3MDY4NzY0Njh9.SR2FGeVS25jbIIw47MnP9Tt9JzqbTWVxeweOwzS0kGw
###